workspace = { members = [
    "src/util",
    "src/ch01",
    "src/ch02",
    "src/ch03",
    "src/ch04",
    "src/ch05",
    "src/ch06",
    "src/ch07",
    "src/ch08",
    "src/ch09",
    "src/ch10",
    "src/ch11",
    "src/ch12",
    "src/ch13",
    "src/ch14",
    "src/ch15",
    "src/ch16",
    "src/ch17",
    "src/ch18",
    "src/ch19",
    "src/ch20",
] }
